use std::collections::HashMap;
use strum_macros::{EnumIter, Display};
use int_enum::IntEnum;

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, EnumIter, Display)]
pub enum Spinners {
    Dots = 0,
    Dots2 = 1,
    Dots3 = 2,
    Dots4 = 3,
    Line = 4,
    GrowVertical = 5,
    Bounce = 6,
    Triangle = 7,
    CircleHalves = 8,
    Clock = 9,
    Earth = 10,
    Moon = 11,
    Men = 12,
    Weather = 13,
    Point = 14,
}

pub fn get_spinner() -> Vec<&'static str> {
    let map_spinner = HashMap::from([
        (Spinners::Dots, vec![
            "⠋",
            "⠙",
            "⠹",
            "⠸",
            "⠼",
            "⠴",
            "⠦",
            "⠧",
            "⠇",
            "⠏",
        ]), (Spinners::Dots2, vec![
            "⠋",
            "⠙",
            "⠚",
            "⠞",
            "⠖",
            "⠦",
            "⠴",
            "⠲",
            "⠳",
            "⠓",
        ]),
        (Spinners::Dots3, vec![
            "⢹",
            "⢺",
            "⢼",
            "⣸",
            "⣇",
            "⡧",
            "⡗",
            "⡏",
        ]),
        (Spinners::Dots4, vec![
            "⢄",
            "⢂",
            "⢁",
            "⡁",
            "⡈",
            "⡐",
            "⡠",
        ]),
        (Spinners::Line, vec![
            "-",
            "\\",
            "|",
            "/",
        ]),
        (Spinners::GrowVertical, vec![
            "▁",
            "▃",
            "▄",
            "▅",
            "▆",
            "▇",
            "▆",
            "▅",
            "▄",
            "▃",
            "▁",
        ]),
        (Spinners::Bounce, vec![
            "⠁",
            "⠂",
            "⠄",
            "⠂",
        ]),
        (Spinners::Triangle, vec![
            "◢",
            "◣",
            "◤",
            "◥",
        ]),
        (Spinners::CircleHalves, vec![
            "◐",
            "◓",
            "◑",
            "◒",
        ]),
        (Spinners::Clock, vec![
            "🕛",
            "🕐",
            "🕑",
            "🕒",
            "🕓",
            "🕔",
            "🕕",
            "🕖",
            "🕗",
            "🕘",
            "🕙",
            "🕚",
        ]),
        (Spinners::Earth, vec![
            "🌍",
            "🌎",
            "🌏",
        ]),
        (Spinners::Moon, vec![
            "🌑",
            "🌒",
            "🌓",
            "🌔",
            "🌕",
            "🌖",
            "🌗",
            "🌘",
        ]),
        (Spinners::Men, vec![
            "🚶",
            "🏃",
        ]),
        (Spinners::Weather, vec![
            "☀️",
            "☀️",
            "☀️",
            "🌤",
            "⛅️",
            "🌥",
            "☁️",
            "🌧",
            "🌨",
            "🌧",
            "🌨",
            "🌧",
            "🌨",
            "⛈",
            "🌨",
            "🌧",
            "🌨",
            "☁️",
            "🌥",
            "⛅️",
            "🌤",
            "☀️",
            "☀️",
        ]),
        (Spinners::Point, vec![
            "∙∙∙",
            "●∙∙",
            "∙●∙",
            "∙∙●",
            "∙∙∙",
        ])
    ]);
    // map_spinner.get(spinner.int_value()).unwrap()
    vec![
        "▁",
        "▃",
        "▄",
        "▅",
        "▆",
        "▇",
        "▆",
        "▅",
        "▄",
        "▃",
        "▁",
    ]

    }